"""
Comprehensive canonical technology taxonomy and alias dictionary for job market analysis.
"""

from typing import Dict, List, Tuple
from stackcheck.models import TechCategory

# Canonical skills mapped to category and standard aliases/keywords
CANONICAL_TAXONOMY: Dict[str, Tuple[TechCategory, List[str]]] = {
    # --- PROGRAMMING LANGUAGES ---
    "Python": (TechCategory.PROGRAMMING_LANGUAGES, ["python", "python3", "py"]),
    "SQL": (TechCategory.PROGRAMMING_LANGUAGES, ["sql", "structured query language", "pl/sql", "tsql", "t-sql"]),
    "R": (TechCategory.PROGRAMMING_LANGUAGES, ["r language", "r programming", " r "]),
    "JavaScript": (TechCategory.PROGRAMMING_LANGUAGES, ["javascript", "js", "ecmascript"]),
    "TypeScript": (TechCategory.PROGRAMMING_LANGUAGES, ["typescript", "ts"]),
    "Java": (TechCategory.PROGRAMMING_LANGUAGES, ["java", "core java", "java 8", "java 11", "java 17", "java 21"]),
    "C++": (TechCategory.PROGRAMMING_LANGUAGES, ["c++", "cpp"]),
    "C#": (TechCategory.PROGRAMMING_LANGUAGES, ["c#", "csharp", ".net c#"]),
    "Go / Golang": (TechCategory.PROGRAMMING_LANGUAGES, ["golang", " go "]),
    "Rust": (TechCategory.PROGRAMMING_LANGUAGES, ["rust", "rustlang"]),
    "Scala": (TechCategory.PROGRAMMING_LANGUAGES, ["scala"]),
    "Julia": (TechCategory.PROGRAMMING_LANGUAGES, ["julia", "julialang"]),
    "SAS": (TechCategory.PROGRAMMING_LANGUAGES, ["sas", "sas programming"]),
    "MATLAB": (TechCategory.PROGRAMMING_LANGUAGES, ["matlab"]),
    "PHP": (TechCategory.PROGRAMMING_LANGUAGES, ["php"]),
    "Ruby": (TechCategory.PROGRAMMING_LANGUAGES, ["ruby", "ruby on rails"]),
    "Kotlin": (TechCategory.PROGRAMMING_LANGUAGES, ["kotlin"]),
    "Bash / Shell": (TechCategory.PROGRAMMING_LANGUAGES, ["bash", "shell scripting", "sh", "zsh"]),
    "DAX": (TechCategory.PROGRAMMING_LANGUAGES, ["dax", "data analysis expressions"]),
    "Power Query / M": (TechCategory.PROGRAMMING_LANGUAGES, ["power query", " m code ", "m language"]),

    # --- BI & VISUALIZATION TOOLS ---
    "Power BI": (TechCategory.BI_DATA_TOOLS, ["power bi", "powerbi", "power-bi", "ms power bi", "microsoft power bi"]),
    "Tableau": (TechCategory.BI_DATA_TOOLS, ["tableau", "tableau desktop", "tableau server", "tableau prep"]),
    "Looker": (TechCategory.BI_DATA_TOOLS, ["looker", "looker studio", "google data studio", "lookml"]),
    "Qlik Sense / QlikView": (TechCategory.BI_DATA_TOOLS, ["qlik", "qlik sense", "qlikview", "qliksense"]),
    "Excel": (TechCategory.BI_DATA_TOOLS, ["excel", "ms excel", "microsoft excel", "advanced excel", "vlookup", "pivot tables"]),
    "Metabase": (TechCategory.BI_DATA_TOOLS, ["metabase"]),
    "Apache Superset": (TechCategory.BI_DATA_TOOLS, ["superset", "apache superset"]),
    "Domo": (TechCategory.BI_DATA_TOOLS, ["domo"]),
    "Sisense": (TechCategory.BI_DATA_TOOLS, ["sisense"]),
    "ThoughtSpot": (TechCategory.BI_DATA_TOOLS, ["thoughtspot"]),
    "MicroStrategy": (TechCategory.BI_DATA_TOOLS, ["microstrategy"]),
    "Google Sheets": (TechCategory.BI_DATA_TOOLS, ["google sheets", "gsheets"]),
    "Alteryx": (TechCategory.BI_DATA_TOOLS, ["alteryx"]),

    # --- DATA ENGINEERING & PLATFORMS ---
    "Snowflake": (TechCategory.DATA_ENGINEERING, ["snowflake", "snowsql", "snowpark"]),
    "Databricks": (TechCategory.DATA_ENGINEERING, ["databricks"]),
    "Apache Spark": (TechCategory.DATA_ENGINEERING, ["spark", "apache spark", "spark streaming"]),
    "PySpark": (TechCategory.DATA_ENGINEERING, ["pyspark"]),
    "dbt (data build tool)": (TechCategory.DATA_ENGINEERING, ["dbt", "data build tool", "dbt core", "dbt cloud"]),
    "Apache Airflow": (TechCategory.DATA_ENGINEERING, ["airflow", "apache airflow"]),
    "Apache Kafka": (TechCategory.DATA_ENGINEERING, ["kafka", "apache kafka"]),
    "Google BigQuery": (TechCategory.DATA_ENGINEERING, ["bigquery", "google bigquery", "bq"]),
    "AWS Redshift": (TechCategory.DATA_ENGINEERING, ["redshift", "amazon redshift", "aws redshift"]),
    "Delta Lake": (TechCategory.DATA_ENGINEERING, ["delta lake", "deltalake"]),
    "Apache Iceberg": (TechCategory.DATA_ENGINEERING, ["iceberg", "apache iceberg"]),
    "Hadoop": (TechCategory.DATA_ENGINEERING, ["hadoop", "hdfs", "hive", "mapreduce"]),
    "Dagster": (TechCategory.DATA_ENGINEERING, ["dagster"]),
    "Prefect": (TechCategory.DATA_ENGINEERING, ["prefect"]),
    "Fivetran": (TechCategory.DATA_ENGINEERING, ["fivetran"]),
    "Airbyte": (TechCategory.DATA_ENGINEERING, ["airbyte"]),
    "Azure Data Factory": (TechCategory.DATA_ENGINEERING, ["azure data factory", "adf", "azure synapse"]),
    "AWS Glue": (TechCategory.DATA_ENGINEERING, ["aws glue", "glue"]),

    # --- DATABASES & STORAGE ---
    "PostgreSQL": (TechCategory.DATABASES_STORAGE, ["postgresql", "postgres", "psql"]),
    "MySQL": (TechCategory.DATABASES_STORAGE, ["mysql"]),
    "Microsoft SQL Server": (TechCategory.DATABASES_STORAGE, ["sql server", "mssql", "microsoft sql server", "ssms", "ssis", "ssas", "ssrs"]),
    "Oracle Database": (TechCategory.DATABASES_STORAGE, ["oracle", "oracle db", "oracle sql"]),
    "MongoDB": (TechCategory.DATABASES_STORAGE, ["mongodb", "mongo"]),
    "Redis": (TechCategory.DATABASES_STORAGE, ["redis"]),
    "Amazon DynamoDB": (TechCategory.DATABASES_STORAGE, ["dynamodb", "dynamo"]),
    "Elasticsearch": (TechCategory.DATABASES_STORAGE, ["elasticsearch", "elastic search", "opensearch"]),
    "ClickHouse": (TechCategory.DATABASES_STORAGE, ["clickhouse"]),
    "Cassandra": (TechCategory.DATABASES_STORAGE, ["cassandra", "apache cassandra"]),
    "Neo4j": (TechCategory.DATABASES_STORAGE, ["neo4j", "graph database"]),
    "Pinecone / Vector DB": (TechCategory.DATABASES_STORAGE, ["pinecone", "milvus", "weaviate", "chromadb", "qdrant", "vector database"]),
    "SQLite": (TechCategory.DATABASES_STORAGE, ["sqlite"]),

    # --- CLOUD & DEVOPS ---
    "AWS": (TechCategory.CLOUD_DEVOPS, ["aws", "amazon web services", "s3", "ec2", "lambda", "athena", "emr", "iam"]),
    "Microsoft Azure": (TechCategory.CLOUD_DEVOPS, ["azure", "microsoft azure", "azure blob", "azure devops"]),
    "Google Cloud Platform (GCP)": (TechCategory.CLOUD_DEVOPS, ["gcp", "google cloud", "google cloud platform", "vertex ai"]),
    "Docker": (TechCategory.CLOUD_DEVOPS, ["docker", "containerization", "containers", "docker-compose"]),
    "Kubernetes": (TechCategory.CLOUD_DEVOPS, ["kubernetes", "k8s", "k8"]),
    "Terraform": (TechCategory.CLOUD_DEVOPS, ["terraform", "iac", "infrastructure as code"]),
    "Git / GitHub": (TechCategory.CLOUD_DEVOPS, ["git", "github", "gitlab", "bitbucket", "version control"]),
    "CI/CD Pipelines": (TechCategory.CLOUD_DEVOPS, ["ci/cd", "ci cd", "continuous integration", "github actions", "gitlab ci", "jenkins"]),
    "Linux": (TechCategory.CLOUD_DEVOPS, ["linux", "unix", "ubuntu", "debian", "redhat", "centos"]),

    # --- AI / ML & ADVANCED ANALYTICS ---
    "Pandas": (TechCategory.AI_ML, ["pandas"]),
    "NumPy": (TechCategory.AI_ML, ["numpy"]),
    "Scikit-learn": (TechCategory.AI_ML, ["scikit-learn", "sklearn", "scikit learn"]),
    "PyTorch": (TechCategory.AI_ML, ["pytorch", "torch"]),
    "TensorFlow": (TechCategory.AI_ML, ["tensorflow", "tf", "keras"]),
    "XGBoost / LightGBM": (TechCategory.AI_ML, ["xgboost", "lightgbm", "catboost"]),
    "Generative AI / LLMs": (TechCategory.AI_ML, ["genai", "generative ai", "llm", "llms", "large language model", "gpt", "rag", "retrieval augmented"]),
    "LangChain": (TechCategory.AI_ML, ["langchain"]),
    "LlamaIndex": (TechCategory.AI_ML, ["llamaindex", "llama index"]),
    "OpenAI API": (TechCategory.AI_ML, ["openai", "chatgpt api"]),
    "Hugging Face": (TechCategory.AI_ML, ["huggingface", "hugging face", "transformers"]),
    "NLP (Natural Language Processing)": (TechCategory.AI_ML, ["nlp", "natural language processing", "spacy", "nltk", "bert"]),
    "Computer Vision": (TechCategory.AI_ML, ["computer vision", "opencv", "yolo", "image processing"]),
    "MLOps": (TechCategory.AI_ML, ["mlops", "mlflow", "kubeflow", "wandb", "weights and biases"]),

    # --- FRAMEWORKS & LIBRARIES ---
    "FastAPI": (TechCategory.FRAMEWORKS_LIBS, ["fastapi", "fast api"]),
    "Django": (TechCategory.FRAMEWORKS_LIBS, ["django", "django rest"]),
    "Flask": (TechCategory.FRAMEWORKS_LIBS, ["flask"]),
    "React": (TechCategory.FRAMEWORKS_LIBS, ["react", "react.js", "reactjs"]),
    "Next.js": (TechCategory.FRAMEWORKS_LIBS, ["next.js", "nextjs"]),
    "Node.js": (TechCategory.FRAMEWORKS_LIBS, ["node.js", "nodejs", "node"]),
    "Express.js": (TechCategory.FRAMEWORKS_LIBS, ["express.js", "expressjs", "express"]),
    "Spring Boot": (TechCategory.FRAMEWORKS_LIBS, ["spring boot", "spring framework", "spring"]),
    "RESTful APIs": (TechCategory.FRAMEWORKS_LIBS, ["rest api", "restful api", "rest apis", "restful apis", "openapi", "swagger"]),
    "GraphQL": (TechCategory.FRAMEWORKS_LIBS, ["graphql"]),
    "Tailwind CSS": (TechCategory.FRAMEWORKS_LIBS, ["tailwind", "tailwindcss"]),

    # --- CORE CONCEPTS & METHODOLOGIES ---
    "Data Modeling": (TechCategory.CORE_CONCEPTS, ["data modeling", "data modelling", "dimensional modeling", "star schema", "snowflake schema", "er diagrams", "3nf"]),
    "ETL / ELT Pipelines": (TechCategory.CORE_CONCEPTS, ["etl", "elt", "data pipeline", "data pipelines", "data ingestion"]),
    "Statistical Analysis": (TechCategory.CORE_CONCEPTS, ["statistical analysis", "statistics", "hypothesis testing", "regression analysis", "anova", "inferential statistics"]),
    "A/B Testing & Experimentation": (TechCategory.CORE_CONCEPTS, ["a/b testing", "ab testing", "experimentation", "controlled experiments", "hypothesis validation"]),
    "Data Governance & Quality": (TechCategory.CORE_CONCEPTS, ["data governance", "data quality", "data lineage", "gdpr", "data catalog"]),
    "Agile / Scrum": (TechCategory.CORE_CONCEPTS, ["agile", "scrum", "kanban", "sprints", "jira"]),
}

# Country to Region Mapping
COUNTRY_TO_REGION = {
    "united states": "USA",
    "usa": "USA",
    "us": "USA",
    "canada": "USA",  # North America cluster
    "united kingdom": "Europe",
    "uk": "Europe",
    "germany": "Europe",
    "france": "Europe",
    "netherlands": "Europe",
    "poland": "Europe",
    "spain": "Europe",
    "italy": "Europe",
    "switzerland": "Europe",
    "sweden": "Europe",
    "ireland": "Europe",
    "pakistan": "Pakistan",
    "pk": "Pakistan",
    "india": "India",
    "in": "India",
    "singapore": "APAC",
    "malaysia": "APAC",
    "japan": "APAC",
    "south korea": "APAC",
    "korea": "APAC",
    "australia": "APAC",
    "new zealand": "APAC",
    "philippines": "APAC",
    "vietnam": "APAC",
    "brazil": "Latin America",
    "mexico": "Latin America",
    "colombia": "Latin America",
    "argentina": "Latin America",
    "united arab emirates": "Middle East",
    "uae": "Middle East",
    "saudi arabia": "Middle East",
}
